DROP DATABASE IF EXISTS blog2;
CREATE DATABASE IF NOT EXISTS blog2 DEFAULT CHARACTER SET 'utf8' ;
USE Blog2;

CREATE TABLE IF NOT EXISTS `admin`(
    `id` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`pseudo` VARCHAR(50) NOT NULL,
	`email` VARCHAR(255) NOT NULL,
	`pass` VARCHAR(99) NOT NULL
)

ENGINE = INNODB;

CREATE TABLE IF NOT EXISTS `article`(
    `id` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`title` VARCHAR(80) NOT NULL,
	`content` LONGTEXT NOT NULL,
	`dateArticle` DATETIME NOT NULL,
	`adminId` INT UNSIGNED,
	CONSTRAINT fk_adminId_id
		FOREIGN KEY (`adminId`),
		REFERENCES `admin`(`id`),
)

ENGINE = INNODB;

CREATE TABLE IF NOT EXISTS `comments`(
	`id` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `author` VARCHAR(50) NOT NULL,
	`comment` LONGTEXT NOT NULL,
	`dateComment` DATETIME NOT NULL,
	`articleId` INT UNSIGNED NOT NULL,
	CONSTRAINT fk_articleId_id
		FOREIGN KEY (`articleId`)
		REFERENCES `article`(`id`),
)   

ENGINE = INNODB;
