DROP DATABASE IF EXISTS Blog;
CREATE DATABASE IF NOT EXISTS Blog DEFAULT CHARACTER SET 'utf8' ;
USE Blog;

CREATE TABLE IF NOT EXISTS user (
	id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	pseudo VARCHAR(50) NOT NULL,
	email VARCHAR(255) NOT NULL,
	pass VARCHAR(255) NOT NULL,
	)

CREATE TABLE IF NOT EXISTS admin(
	id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	pseudo VARCHAR(50) NOT NULL,
	email VARCHAR(255) NOT NULL,
	pass VARCHAR(99) NOT NULL)
	)

CREATE TABLE IF NOT EXISTS article(
	id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	title VARCHAR(80) NOT NULL,
	content LONGTEXT NOT NULL,
	dateArticle DATETIME NOT NULL,
	adminId INT UNSIGNED,
	CONSTRAINT fk_adminId_id
		FOREIGN KEY (adminId)
		REFERENCES admin(id)
	)

CREATE TABLE IF NOT EXISTS  comments (
	id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	content LONGTEXT NOT NULL,
	dateComment DATETIME NOT NULL,
	idParent INT NOT NULL DEFAULT 0,
	userId INT UNSIGNED,
	articleId INT UNSIGNED NOT NULL,
	CONSTRAINT fk_userId_id
		FOREIGN KEY (userId)
		REFERENCES user(id),

	CONSTRAINT fk_articleId_id
		FOREIGN KEY (articleId)
		REFERENCES article(id),
	)